### PR TITLE
Update 311-DEV.yaml

### LINKED ISSUE #407: add `esda` bleeding edge to `DEV` testing
@martinfleis Do you see any drawback to adding the bleeding edge `esda` to [`ci/311-DEV.yaml`](https://github.com/pysal/spopt/blob/main/ci/311-DEV.yaml)?

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR resolves #407

### CODE REVIEW

**Comment by martinfleis** [comment]
But spopt does not seem to depend on esda... Am I missing anything? Is that a dependency via another package?

**Comment by jGaboardi** [comment]
> But spopt does not seem to depend on esda... Am I missing anything? Is that a dependency via another package?

Yes, `spaghetti`.

**Comment by martinfleis** [comment]
Not sure how deep we need to go but it won't hurt for sure.

**Comment by jGaboardi** [comment]
Yeah, if the failure wasn't in the PySAL ecosystem then I wouldn't be as for this.

**Pull request merged**
