### PR TITLE
Clean up the implementation of the capacitated LSCP

### LINKED ISSUE #320: clean up CLSCP-SO implementation
Following up with #316:
* [x] clean up error messages, etc. in:
  * [`add_facility_capacity_constraint`](https://github.com/pysal/spopt/blob/8e6b1927076f2c6b15ec61c0f7690ff0027d5eb7/spopt/locate/base.py#L488) -> aa02fdf
  * [`add_client_demand_satisfaction_constraint`](https://github.com/pysal/spopt/blob/8e6b1927076f2c6b15ec61c0f7690ff0027d5eb7/spopt/locate/base.py#L531) -> aa02fdf
* [x] add warnings/errors testing for the above in [`test_clscp-so.py`](https://github.com/pysal/spopt/blob/8e6b1927076f2c6b15ec61c0f7690ff0027d5eb7/spopt/tests/test_clscp-so.py#L15) à la [`TestErrorsWarnings`](https://github.com/pysal/spopt/blob/8e6b1927076f2c6b15ec61c0f7690ff0027d5eb7/spopt/tests/test_lscpb.py#L283)
* [x] review & spruce notebook -> 08b6cfd
   * review formulation & terminology
   * update & add references
   * review demonstration scenario
   * add more complex scenario
   * maybe comparison of CLSCP-SO to LSCP ~~and LSCP-B~~
   * update plots
* [x] review docstrings -> b6e1f11
   * add model formulation and explanation in the LSCP docs
   * add references there
* [x] update `docs/`
   * add to `references.bib` -> 09c7911
   * add notebook to Tutorials list -> 1b003e5
   * ensure proper build & rendering + check API rendering

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR resolves #320.

### CODE REVIEW

**Comment by gegen07** [comment]
@jGaboardi Sorry for the delay. I'll have time to review it tomorrow 😬

**Comment by jGaboardi** [comment]
> @jGaboardi Sorry for the delay. I'll have time to review it tomorrow 😬

Awesome! And no worries. Thanks for taking the time (when you have it)!

**Review by gegen07 — CHANGES_REQUESTED** [review]
- In `Assign simulated points network locations` section, I think there is a typo. It is written _The simulated client and facility points do not *ahere* to network space._ It is supposed to be *adhere*? I noted this word in all notebooks that explain a model. 

- There is a typo in `lscp_capacity.ipynb` in scenario 4. It is written _internel_ instead of _internal_. 

These questions are perfectionism, all notebooks are brilliant.

**Comment by jGaboardi** [comment]
I love thorough review and greatly appreciate the detailed comb through. I'll make these changes, and then we'll be OK for a merge (if everything else looks OK)?

**Pull request merged**
