### PR TITLE
add azp into spopt

### PR DESCRIPTION
**Pull request by xf37**

### CODE REVIEW

**Review by jGaboardi — COMMENTED** [review]
Looks like it's something upstream on Ubuntu, but we need to work out what's causing the [failures](https://github.com/pysal/spopt/pull/75/checks?check_run_id=1476836423#step:8:12).


```

**Comment by xf37** [comment]
> cropping up
Yeah, I checked some websites, no clue yet :(
https://github.com/facebookresearch/habitat-lab/issues/411

**Comment by jGaboardi** [comment]
> Yeah, I checked some websites, no clue yet :(
> [facebookresearch/habitat-lab#411](https://github.com/facebookresearch/habitat-lab/issues/411)

Is `facebookresearch/habitat-lab` being used here? Seems like [`fiona` might be the troublemaker](https://github.com/pysal/spopt/pull/75/checks?check_run_id=1476836423#step:8:21). At any rate, there's really nothing we can do here for the moment except wait and see what happens.

**Review by jGaboardi — COMMENTED** [review]
In terms of actual code this seems OK, but I think we should get a review from a regionalization person (@rwei5 , @sjsrey, @knaaptime?). However, while 100% code coverage is generally not practical, there is a shockingly low percentage of covered lines of code in the AZP for new functionality (`azp.py`-35.8%, `azp_util.py`-36.3%, `util.py`-47.6%, and `objective_function.py`-59.6%). There should be more tests included to check the functionality of edge cases.

**Comment by xf37** [comment]
> In terms of actual code this seems OK, but I think we should get a review from a regionalization person (@rwei5 , @sjsrey, @knaaptime?). However, while 100% code coverage is generally not practical, there is a shockingly low percentage of covered lines of code in the AZP for new functionality (`azp.py`-35.8%, `azp_util.py`-36.3%, `util.py`-47.6%, and `objective_function.py`-59.6%). There should be more tests included to check the functionality of edge cases.

Okay. Let's see. I will continue to fulfill the parts of the comment. The parameters and examples are not fully provided in some cases.

**Comment by jGaboardi** [comment]
> Okay. Let's see. I will continue to fulfill the parts of the comment. The parameters and examples are not fully provided in some cases.

Excellent. Also, having empirical test cases (like the Mexico example) is very important. But equally important is having small, synthetic test cases where we know exactly the answer. Especially with regionalization this can be achieved with small lattice (e.g. 3x3, 9x9, etc. tessellation) while varying input parameters (e.g. `n_clusters`, `allow_move_strategy`, `random_state` in AZP).

Let me know if you need any assistance with this or want to toss around ideas.

**Pull request merged**
