### PR TITLE
attempt 3.9 testing

### PR DESCRIPTION
**Pull request by jGaboardi**
This PR is the initial attempt to support Python 3.9 for CI testing.

### CODE REVIEW

**Comment by jGaboardi** [comment]
See original PR in #71.

**Comment by jGaboardi** [comment]
Dependencies not yet there for 3.9. Leaving this open for now and will check back periodically.

Looks like the specific failure [here](https://github.com/pysal/spopt/pull/71/checks?check_run_id=1459547251) is:

```
numpy[version='>=1.3'] -> blas=[build=mkl] -> liblapacke==3.8.0[build='4_mkl|5_mkl|6_mkl|9_mkl|11_mkl|14_mkl|16_mkl|21_mkl|20_mkl|19_mkl|18_mkl|15_mkl|13_mkl|12_mkl|10_mkl|8_mkl|7_mkl']
```

**Comment by knaaptime** [comment]
how come we're pinning scikit to 0.22?

**Comment by jGaboardi** [comment]
> how come we're pinning scikit to 0.22?

No idea. Let's try without a pinned version?

**Comment by knaaptime** [comment]
this is supreceded by #95

**Pull request closed without merging**
