### PR TITLE
Add predefined locations to coverage models

### PR DESCRIPTION
**Pull request by gegen07**
Based on ideas raised in discussion #218. 
I'm trying to implement @jGaboardi idea, for instance.

### CODE REVIEW

**Comment by jGaboardi** [comment]
This is a very nice start @gegen07!

**Comment by jGaboardi** [comment]
I just realized that we are not assigning decision variable labels for plotting, but only using the `range` (see [`plot_results`](https://github.com/pysal/spopt/blob/72059b2c6d0c06025905277c83b3bb8e8600fe83/notebooks/mclp.ipynb) in the MCLP notebook). By doing this we have the same labels for the solution facilities in "cost matrix" and "geodataframe" examples, though the selection set is different. In order to ensure comparable results (and confirm the preselected facilities are being adhered to) we need to label the facilities from a static index (e.g. decision variable label from the `pulp` model) and also ensure a 1:1 color scheme (e.g.

**Comment by gegen07** [comment]
In the MCLP notebook we have different labels in the legend. We are not getting the label from the pulp model to create the facility-client matrix. When do you say create a static index you mean to get the labels from pulp, like another method to get these labels, or just assign a 1:1 dictionary in the `plot_results` method using the indexes of the facility-client matrix?

**Comment by jGaboardi** [comment]
> In the MCLP notebook we have different labels in the legend.
> We are not getting the label from the pulp model to create the facility-client matrix. When do you say create a static index you mean to get the labels from pulp, like another method to get these labels, or just assign a 1:1 dictionary in the `plot_results` method using the indexes of the facility-client matrix?

ah! You are right about that, I completely misread the legend. My fault. Though it is still good to have a defined color map so that a specific color is tied to a specific facility. Then the two plots in the notebook are easier to compare.

**Review by jGaboardi — APPROVED** [review]
This is unbelievably great work @gegen07. Let's also try to get a reviews from Qunshan and Levi if they have time. But it looks great to me.

**Comment by jGaboardi** [comment]
I think this is probably good to go and we can go ahead and merge. 🎉

**Comment by qszhao** [comment]
Thanks @jGaboardi and @gegen07! Great to have this question sorted out!

**Pull request merged**
