### PR TITLE
add Church & Murray Business Site Selection to refs

### PR DESCRIPTION
**Pull request by rongboxu**
#380 

If the reference has any problem, please let me know!

### CODE REVIEW

**Review by jGaboardi — APPROVED** [review]
This looks good to me! 

On a side note, I'm wondering if you are also intending to be opening and committing to PRs over in @ljwolf's branch (https://github.com/ljwolf/spopt/pull/2)?

**Comment by rongboxu** [comment]
> 

Thank you for merging it!

I think my later changes can be over my forked repository of original spopt, considering that the capacitated changes have been merged?

**Comment by jGaboardi** [comment]
> I think my later changes can be over my forked repository of original spopt, considering that the capacitated changes have been merged?

Correct.

**Comment by rongboxu** [comment]
> > I think my later changes can be over my forked repository of original spopt, considering that the capacitated changes have been merged?
> 
> Correct.

Hi James! Sorry I have one more question. I can't create a new forked repository of original spopt, because it shows that I already have one forked from Levi's. Should I delete the old one now? And will it influence the previous commits happening on this old forked repository?

**Comment by jGaboardi** [comment]
> Hi James! Sorry I have one more question. 

No problem!

> I can't create a new forked repository of original spopt, because it shows that I already have one forked from Levi's. Should I delete the old one now? And will it influence the previous commits happening on this old forked repository?

This is a good question and I am not sure. Perhaps either archiving or deleting your fork of Levi's fork. But let's no try that yet. There is probably a much safer solution. @gegen07 @ljwolf Do either of you have any insight on this?

**Comment by ljwolf** [comment]
Forks of forks are the same as forks for git's purposes... the only difference I'm aware of is that GitHub will default your pull requests to ljwolf/spopt instead of pysal/spopt. The change in workflow is that you have to select pysal/spopt instead of ljwolf/spopt as the "target" of your pull request. But, we have to do this anyway when working on branches! 

Remaking the fork would set the initial target for PRs correctly, and also ensure our stats on pysal/spopt are "correct." 

My understanding is that you do this by deleting your fork and then making a new fork from pysal/spopt. Since "rongboxu/spopt" remains the same, nothing has to change on your local computer; it's only GitHub that needs to be "fixed." 

We can walk through this on Tuesday?

**Comment by rongboxu** [comment]
> Forks of forks are the same as forks for git's purposes... the only difference I'm aware of is that GitHub will default your pull requests to ljwolf/spopt instead of pysal/spopt. The change in workflow is that you have to select pysal/spopt instead of ljwolf/spopt as the "target" of your pull request. But, we have to do this anyway when working on branches!
> 
> Remaking the fork would set the initial target for PRs correctly, and also ensure our stats on pysal/spopt are "correct."
> 
> My understanding is that you do this by deleting your fork and then making a new fork from pysal/spopt. Since "rongboxu/spopt" remains the same, nothing has to change on your local computer; it's only GitHub that needs to be "fixed."
> 
> We can walk through this on Tuesday?

Thank you for explaining all of this! I am afraid of deleting it but it seems that only keeping 1 forked repository is the requirement.

Does remaking the fork also mean that a new pull request need to be made? But the capacitated p-median pull request has been merged...

It's so interesting and challenging to understand how git and Github works!

**Comment by ljwolf** [comment]
> Does remaking the fork also mean that a new pull request need to be made? 

It's kind of complicated. 

If the PR is closed/merged (like yours is), **no**, nothing needs to change. 

If the PR is open _and no new changes are needed_, then **no**, GitHub stores a copy in the PR itself. 

If you have an open PR _that will need to be updated in the future_, **yes**, I believe you would have to push that material back up to rongboxu/spopt after making your new fork, and then make a new PR once you have done so. I don't think GitHub recognizes when you update the branch in your new fork, since the PR "comes from" the old fork. But I'm not sure!

**Comment by rongboxu** [comment]
> > Does remaking the fork also mean that a new pull request need to be made?
> 
> It's kind of complicated.
> 
> If the PR is closed/merged (like yours is), **no**, nothing needs to change.
> 
> If the PR is open _and no new changes are needed_, then **no**, GitHub stores a copy in the PR itself.
> 
> If you have an open PR _that will need to be updated in the future_, **yes**, I believe you would have to push that material back up to rongboxu/spopt after making your new fork, and then make a new PR once you have done so. I don't think GitHub recognizes when you update the branch in your new fork, since the PR "comes from" the old fork. But I'm not sure!

Thank you for the reply! It makes sense to me! It seems that if any changes will be made after making the new fork, Github can't recognise it, therefore I should make a new PR?

Thank you again! And I think it's better that we can walk through it together next Tuesday!!

**Pull request merged**
