### PR TITLE
Add paper

### PR DESCRIPTION
**Pull request by xf37**

### CODE REVIEW

**Comment by jGaboardi** [comment]
@xf37 Once you create the review issue in the JOSS repo, PDFs are can be generated automatically with [whedon](https://github.com/openjournals/joss-reviews/issues/2826#issuecomment-723988479).

**Comment by xf37** [comment]
> @xf37 Once you create the review issue in the JOSS repo, PDFs are can be generated automatically with [whedon](https://github.com/openjournals/joss-reviews/issues/2826#issuecomment-723988479).

@jGaboardi Thanks James for looking into this. I visited https://whedon.theoj.org and entered our repository address. However the PDFs automatically generated contain several unexpected typos. Please see the screenshots below. Do you know how to fix it?
Screen Shot 2021-05-14 at 6 49 18 PM
Screen Shot 2021-05-14 at 6 49 34 PM

**Comment by jGaboardi** [comment]
@xf37 I pushed up some formatting changes in the citations that may make a difference. Multi-citations should be:
`[@cite1;@cite2]` not `[@cite1][@cite2]`.

**Comment by jGaboardi** [comment]
Although I would still say that getting the submission into review is the :top: priority, then we can work out formatting through the review process.

**Pull request merged**
