### PR TITLE
address new `ruff` failures

### PR DESCRIPTION
**Pull request by jGaboardi**
~~***EDIT*** On hold until more insight from https://github.com/pysal/momepy/pull/476.~~

This PR:
* follows up #359 with fixes for the fresh `ruff` failures.
* supersedes #361

### CODE REVIEW

**Review by martinfleis — COMMENTED** [review]
I'll leave the decision on how precise you want stack levels to be to you but wanted to flag that `stacklevel=1` is always wrong one (not informative), so you may want to revisit it if you thought it has proper levels. We should generally try to show the level of a user call to a function that caused the warning. E.g.

```py
from warnings import warn

def fn():
    warn("my warn", stacklevel=2)

fn()
```

which shows 
```
.../file.py:1: UserWarning: my warn
  fn()
```

That tells you that the warning is caused by a call to `fn()`. While `stacklevel=1` shows

```
.../file.py:1: UserWarning: my warn
  warn("my warn", stacklevel=1)
```

which is not useful.

**Comment by jGaboardi** [comment]
Ah. I'll give this some more thought.

**Comment by jGaboardi** [comment]
@martinfleis OK, I think I understand this now and that proper stack levels are being applied.

**Review by martinfleis — APPROVED** [review]
Looking good!

**Pull request merged**
